Controllers/TaikhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Doan.Model;


namespace Doan.Controllers
{
    public class TaikhoanController : Controller
    {
        ShopOnline_DemoEntities1 db = new ShopOnline_DemoEntities1();
        // GET: Taikhoan
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection col, TaiKhoan tk )
        {
            var tendn = col["TenDN"];
            var mk = col["Matkhau"];
            var e = col["Email"];
            var dc = col["DiaChi"];
            var sdt = col["SoDT"];
            if (string.IsNullOrEmpty(tendn))
            {
                ViewData["loi1"] = " Tên đăng nhập là thông tin bắt buộc  ";
            }
            if (string.IsNullOrEmpty(mk))
            {
                ViewData["loi2"] = " Mật khẩu là thông tin bắt buộc ";
            }
            if (string.IsNullOrEmpty(e))
            {
                ViewData["loi3"] = " Email là thông tin bắt buộc ";
            }
            if (string.IsNullOrEmpty(dc))
            {
                ViewData["loi4"] = " Địa chỉ là thông tin bắt buộc ";
            }
            if (string.IsNullOrEmpty(sdt))
            {
                ViewData["loi5"] = " Số điện thoại là thông tin bắt buộc ";
            }
            else
            {
                tk.tenTV= tendn;
                tk.matKhau= mk;
                 tk.email = e;
                tk.diaChi= dc;
                tk.soDT= sdt;
              
                return RedirectToAction("Dangnhap");
            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection col)
        {
            var tendn = col["TenDN"];
            var mk = col["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["loi1"] = " Tên đăng nhập là thông tin bắt buộc ";
            }
            else if (String.IsNullOrEmpty(mk))
            {
                ViewData["loi2"] = " Mặt khẩu là thông tin bắt buộc ";
            }
            else
            {
                TaiKhoan tk  = db.TaiKhoans.SingleOrDefault(n => n.tenTV == tendn && n.matKhau == mk);
                if (tk != null)
                {
                    //ViewBag.ThongBao = "Chào mừng đăng nhập thành công";
                    Session["TaiKhoan"] =tk;
                    return RedirectToAction("Giohang", "GioHang");

                }
                else ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng ";
            }
            return View();
        }


    }
}

Views/Taikhoan/Dangky.cshtml
@{
    Layout = null;
}
<div class="container" id="khochua" style="margin-top:30px;">
    <!--Form 2-->

    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div action="/action_page.php" style="text-align:center;margin: 5% 30% 5% 30%">
            <h2>Đăng ký</h2>
            <div class="form-group">
                <label class="textL" for="text">Tên tài khoản <span class="do">*</span></label>
                <input type="text" class="form-control khungForm" id="TenDN" name="TenDN">
                <div style="color:red">@ViewData["loi1"]</div>
            </div>
            <div class="form-group">
                <label class="textL" for="email">Địa chỉ Email <span class="do">*</span></label>
                <input type="email" class="form-control khungForm" id="email" name="Email">
                <div style="color:red">@ViewData["loi3"]</div>
            </div>
            <div class="form-group">
                <label class="textL" for="pwd">Mật khẩu <span class="do">*</span></label>
                <input type="password" class="form-control khungForm" id="pwd" name="Matkhau">
                <div style="color:red">@ViewData["loi2"]</div>
            </div>
            <div class="form-group">
                <label class="textL" for="text">Địa chỉ khách hàng <span class="do">*</span></label>
                <input type="text" class="form-control khungForm" id="DiaChi" name="DiaChi">
                <div style="color:red">@ViewData["loi4"]</div>
            </div>
            <div class="form-group">
                <label class="textL" for="text">Số điện thoại khách hàng <span class="do">*</span></label>
                <input type="text" class="form-control khungForm" id="SoDT" name="SoDT">
                <div style="color:red">@ViewData["loi5"]</div>
            </div>
            <div class="text1">
                <p>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our <a href="Chính sách riêng tư.html">chính sách riêng tư.</a></p>
            </div>
            <input type="submit" class="buttom" name="Đăng ký" value="Đăng ký" />
            <p style="margin-top:2%">Đã có Tài Khoản ?</p>
            <input type="button" class="buttom" name="Đăng nhập" value="Đăng nhập" onclick="location.href='@Url.Action("Dangnhap", "Taikhoan")'" />
        </div>
    }
</div>

Views/Taikhoan/Dangnhap.cshtml
@{
    Layout = null;
}

<h4 style="color:red; text-align:center; ">@ViewBag.Thongbao</h4>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true);
    <div action="/action_page.php" style="text-align:center;margin: 5% 35% 5% 35%">
        <h2>Đăng nhập</h2>
        <div class="form-group">
            <label class="textL" for="email text">Tên tài khoản: <span class="do">*</span></label>
            <input type="text" class="form-control khungForm" id="TenDN" name="TenDN">
            <div style="color:red">@ViewData["loi1"]</div>
        </div>
        <div class="form-group">
            <label class="textL" for="pwd">Mật khẩu <span class="do">*</span></label>
            <input type="password" class="form-control khungForm" id="Matkhau" name="Matkhau">
            <div style="color:red"> @ViewData["loi2"]</div>
        </div>
        <input type="submit" class="buttom" name="Đăng nhập" value="Đăng nhập" />
        <p style="margin-top:2%">Chưa có Tài Khoản ?</p>
        <input type="button" class="buttom" name="Đăng ký" value="Đăng ký" onclick="location.href='@Url.Action("Dangky", "Taikhoan")'" />
        @*<p style="margin-top:2%">Đến giỏ hàng ?</p>
            <input type="button" class="buttom" name="Đến giỏ hàng" value="Đến giỏ hàng" onclick="location.href='@Url.Action("Giohang", "GioHang")'" />*@
    </div>

}